apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged-containers
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-privileged
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          Los contenedores no deben ejecutarse en modo privilegiado.
        pattern:
          spec:
            containers:
              - securityContext:
                  privileged: "false"
