apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-image-tag
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
                - CronJob
      validate:
        message: >-
          Prohibido usar imágenes `:latest`. Usar una versión explícita o digest.
        pattern:
          spec:
            template:
              spec:
                containers:
                  - image: "!*:latest"
