apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.16.1 # O la versión que prefieras
    helm:
      releaseName: cert-manager
      values: |
        # Campo correcto para instalar CRDs
        crds:
          enabled: true
        
        # Configuración del controlador
        replicaCount: 1
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        
        # Configuración del cainjector (sin cambios)
        cainjector:
          enabled: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
        
        # Configuración del webhook (SIN 'enabled')
        webhook:
          timeoutSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true